(define (accumulate op initial sequence)
  (if (null? sequence)
      initial
      (op (car sequence)
	  (accumulate op initial (cdr sequence)))
      ))
(define (flatmap proc seq)
  (accumulate append '() (map proc seq)))
(define (enumerate-interval a b)
  (if (>= a b)
      (list b)
      (cons a (enumerate-interval (+ a 1) b))))
(define (queens board-size)
  (define (queen-cols i)
    (if (= i 0)
	(list (empty-board))
	(filter
	 (lambda (positions) (safe? positions))
	 (flatmap
	  (lambda (rest-of-queens)
	    (map (lambda (j)
		   (adjoin-position i j rest-of-queens))
		 (enumerate-interval 1 board-size)))
	  (queen-cols (- i 1))))
	))
  (queen-cols board-size)
  )
(define (empty-board) (list))
(define (adjoin-position i j rest-of-queens)
  (cons (cons i j) rest-of-queens))
(define (safe? positions)
  (define (safe-row? j positions)
    (eq? '()
	 (filter (lambda (y) (= y j))
		 (map (lambda (p) (cdr p)) (cdr positions))
		 )))
  (define (safe-add? s positions)
    (eq? '()
	 (filter (lambda (e) (= e s))
		 (map (lambda (p) (+ (car p) (cdr p))) (cdr positions))
		 )))
  (define (safe-dec? d positions)
    (eq? '()
	 (filter (lambda (e) (= e d))
		 (map (lambda (p) (- (car p) (cdr p))) (cdr positions))
		 )))
  (and (safe-row? (cdar positions) positions)
       (safe-add? (+ (caar positions) (cdar positions)) positions)
       (safe-dec? (- (caar positions) (cdar positions)) positions))
  )
(queens 8)
