(define (same-even a l)
  (cond ((null? l) '())
	((= (remainder a 2) (remainder (car l) 2))
	 (cons (car l) (same-even a (cdr l))))
	(else (same-even a (cdr l)))
      ))
(define (same-partiy a . l)
  (same-even a l))
(same-partiy 1 3 4 5 6 7)
